# Azure SQL servers per environment. Private Link addresses — reachable only over VPN.
# Source: Confluence, "Systemdokumentasjon Altinn Infoportal" -> AzureSQL
#
# env  host                                                        blob-account
at22   infop-at22-vllfov-server.privatelink.database.windows.net   infoportalmediaat224w17
at23   infop-at23-vtjzsk-server.privatelink.database.windows.net   infoportalmediaat23n73s
tt02   infop-tt02-ksalae-server.privatelink.database.windows.net   infoportalmediatt02q9ew
prod   infop-prod-hxhapc-server.privatelink.database.windows.net   infoportalmediaprodl08r
