#!/usr/bin/env bash
#
# Start a local SQL Server (or Azure SQL Edge) container and wait until it
# accepts connections. All writes are local; nothing here touches a remote
# environment.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
. "$SCRIPT_DIR/lib.sh"

ENV_FILE="$SCRIPT_DIR/.env"
CONTAINER_NAME="infoportal-mssql"
RECREATE=1

usage() {
  cat >&2 <<EOF
usage: start-sqlserver.sh [--keep] [--port N]

  --keep     reuse a running container instead of recreating it
  --port N   host port to publish (default 1433, or MSSQL_PORT in .env)
EOF
  exit 1
}

PORT_OVERRIDE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --keep) RECREATE=0; shift ;;
    --port) [ $# -ge 2 ] || usage; PORT_OVERRIDE="$2"; shift 2 ;;
    -h|--help) usage ;;
    *) log "unknown option: $1"; usage ;;
  esac
done

if [ -n "$PORT_OVERRIDE" ]; then
  case "$PORT_OVERRIDE" in
    ''|*[!0-9]*) die "invalid --port value '$PORT_OVERRIDE': must be a number" ;;
  esac
fi

require_sqlcmd

# --- .env -------------------------------------------------------------------
# Sourced before the runtime is touched, so CONTAINER_CLI can be set here as
# well as in the environment.
if [ -f "$ENV_FILE" ]; then
  # shellcheck source=/dev/null
  . "$ENV_FILE"
fi

# Verify the pinned connection before anything wraps a cre call in a redirect
# or a `|| true`, either of which would swallow this check's message.
require_container_connection

# SQL Server refuses to start below 2GB.
# podman's info template nests this under .Host; docker's has it top-level
# with no .Host key at all, so try both.
MEM_BYTES="$(cre info --format '{{.Host.MemTotal}}' 2>/dev/null || cre info --format '{{.MemTotal}}' 2>/dev/null || echo 0)"
case "$MEM_BYTES" in ''|*[!0-9]*) MEM_BYTES=0 ;; esac
if [ "$MEM_BYTES" -gt 0 ] && [ "$MEM_BYTES" -lt 2147483648 ]; then
  log "warning: container runtime reports $((MEM_BYTES / 1048576))MB available;"
  log "SQL Server needs at least 2GB and will fail to start below that."
fi

# --- choose the image -------------------------------------------------------
# Real SQL Server is the default everywhere, because it is the engine the
# environments actually run. It is native on x86_64, and on Apple Silicon it
# runs under Rosetta-backed emulation (Colima --vm-type=vz --vz-rosetta, or
# Docker Desktop with Rosetta enabled) -- verified working.
#
# It does NOT run under qemu user-mode emulation, which is podman's default on
# macOS: it segfaults on startup. That case is not probed for -- binfmt_misc is
# per-namespace so a container can never see the host's handlers -- it is
# detected from the actual crash in the readiness wait below, which is reliable.
#
# Azure SQL Edge remains available as an arm64-native fallback for machines
# without Rosetta; set MSSQL_IMAGE and MSSQL_PLATFORM in scripts/db/.env.
choose_image() {
  printf 'mcr.microsoft.com/mssql/server:2022-latest linux/amd64\n'
}

if [ -z "${MSSQL_SA_PASSWORD:-}" ]; then
  MSSQL_SA_PASSWORD="$(printf '%sAa1' "$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | cut -c1-20)")"
fi
[ -n "$PORT_OVERRIDE" ] && MSSQL_PORT="$PORT_OVERRIDE"
MSSQL_PORT="${MSSQL_PORT:-1433}"

if [ -z "${MSSQL_IMAGE:-}" ]; then
  read -r MSSQL_IMAGE MSSQL_PLATFORM <<EOF
$(choose_image)
EOF
fi
# Setting only MSSQL_IMAGE externally (e.g. in .env, to opt into real SQL
# Server on arm64) must not leave MSSQL_PLATFORM unset under `set -u`.
MSSQL_PLATFORM="${MSSQL_PLATFORM:-linux/amd64}"

umask 077
cat >"$ENV_FILE" <<EOF
# Generated by start-sqlserver.sh. Local development only; git-ignored.
MSSQL_SA_PASSWORD='$MSSQL_SA_PASSWORD'
MSSQL_PORT=$MSSQL_PORT
MSSQL_IMAGE=$MSSQL_IMAGE
MSSQL_PLATFORM=$MSSQL_PLATFORM
EOF
chmod 600 "$ENV_FILE"

log "image: $MSSQL_IMAGE ($MSSQL_PLATFORM), port $MSSQL_PORT"

COMPOSE_ARGS="--env-file $ENV_FILE -f $INFOPORTAL_REPO_ROOT/docker-compose.yml --project-name infoportal --profile localdb"

start_container_fresh() {
  # Targeted teardown. Never `compose down -v`: that removes every named volume
  # in the project, including umbraco_logs, umbraco_data and umbraco_media.
  #
  # The project name is pinned above (--project-name infoportal) rather than
  # derived from the checkout directory: compose sanitizes its default project
  # name (lowercased, non [a-z0-9_-] characters stripped), so a directory like
  # "info.altinn.no" would resolve to volume "infoaltinnno_mssql_data" while a
  # naive basename-derived name would not match, silently orphaning teardown.
  # shellcheck disable=SC2086
  compose $COMPOSE_ARGS stop mssql >/dev/null 2>&1 || true
  # shellcheck disable=SC2086
  compose $COMPOSE_ARGS rm -f mssql >/dev/null 2>&1 || true
  cre volume rm infoportal_mssql_data >/dev/null 2>&1 || true
  # shellcheck disable=SC2086
  compose $COMPOSE_ARGS up -d mssql
}

# --- start ------------------------------------------------------------------
if [ "$RECREATE" -eq 1 ]; then
  log "recreating container ..."
  start_container_fresh
else
  if cre ps --format '{{.Names}}' | grep -qx "$CONTAINER_NAME"; then
    log "reusing running container $CONTAINER_NAME"
  else
    start_container_fresh
  fi
fi

# --- wait for readiness -----------------------------------------------------
# Polled from the host: the Azure SQL Edge image ships no mssql-tools, so an
# in-container healthcheck cannot work for both images.
log "waiting for the database to accept connections ..."
WAITED=0
until run_sqlcmd -S "localhost,$MSSQL_PORT" -U sa -P "$MSSQL_SA_PASSWORD" -C -Q "SELECT 1" >/dev/null 2>&1; do
  # Don't just wait out the clock: if the engine died, say why now.
  RUNNING="$(cre inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null || echo unknown)"
  if [ "$RUNNING" = "false" ]; then
    EXIT_CODE="$(cre inspect -f '{{.State.ExitCode}}' "$CONTAINER_NAME" 2>/dev/null || echo '?')"
    log "container logs:"
    cre logs "$CONTAINER_NAME" 2>&1 | tail -15 >&2
    if [ "$EXIT_CODE" = "139" ]; then
      die "SQL Server segfaulted on startup (exit 139).

That means your container runtime is emulating x86 with qemu rather than
Rosetta. SQL Server does not survive qemu user-mode emulation.

Either use a Rosetta-backed runtime -- Colima:
  colima start --vm-type=vz --vz-rosetta --cpu 4 --memory 8
  CONTAINER_CLI=\$(command -v docker)   # must be a real docker, not the podman shim
or fall back to the arm64-native engine by putting this in scripts/db/.env:
  MSSQL_IMAGE=mcr.microsoft.com/azure-sql-edge
  MSSQL_PLATFORM=linux/arm64
(Azure SQL Edge is a reduced engine and not what the environments run.)"
    fi
    die "the database container exited (code $EXIT_CODE) before becoming ready"
  fi

  if [ "$WAITED" -ge 180 ]; then
    log "container logs:"
    cre logs "$CONTAINER_NAME" 2>&1 | tail -20 >&2
    die "database did not become ready within 180s"
  fi
  sleep 5
  WAITED=$((WAITED + 5))
done

log "ready after ${WAITED}s"
printf '%s\n' "$MSSQL_SA_PASSWORD"
