apiVersion: vault.dis.altinn.cloud/v1alpha1
kind: Vault
metadata:
  name: umbraco
spec:
  serviceAccountRef:
    name: umbraco
  groupObjectId: 42688626-6503-4d1d-8aa4-e1e5fef2b4be
  tags:
    app: infoportal
