apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: elasticsearch-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://infoportal-es-tt02-6i5q.vault.azure.net"
      serviceAccountRef:
        name: umbraco
