apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: elasticsearch-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      tenantId: "cd0026d8-283b-4a55-9bfa-d0ef4a8ba21c"
      vaultUrl: "https://infoportal-es-tt02-6i5q.vault.azure.net"
      serviceAccountRef:
        name: umbraco
