apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

images:
- name: umbraco

patches:
  - target:
      kind: HTTPRoute
      name: umbraco
    patch: |-
      - op: add
        path: /spec/hostnames
        value:
          - infoportal.tt02.dis-core.altinn.cloud
