apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-infoportal
resources:
  - ../base

images:
  - name: umbraco
    newName: altinncr.azurecr.io/ghcr.io/altinn/umbraco
    newTag: will-be-replaced

patches:
  - target:
      kind: Vault
      name: umbraco
    patch: |-
      - op: add
        path: /spec/tags/env
        value: at23
  - target:
      kind: Deployment
      name: umbraco
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Umbraco__Storage__AzureBlob__Media__ConnectionString
          value: https://infoportalmediaat23n73s.blob.core.windows.net
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Umbraco__Storage__AzureBlob__Media__ContainerName
          value: umbraco
  - target:
      kind: HTTPRoute
      name: umbraco
    patch: |-
      - op: add
        path: /spec/hostnames
        value:
          - infoportal.at23.dis-core.altinn.cloud
