apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: elasticsearch-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      environmentType: PublicCloud
      vaultUrl: "https://infoportal-es-prod-08hv.vault.azure.net"
      serviceAccountRef:
        name: umbraco
      useAzureSDK: false
