apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elasticsearch
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: elasticsearch-keyvault
    kind: SecretStore
  target:
    name: elasticsearch
    creationPolicy: Owner
  data:
    - secretKey: endpoint
      remoteRef:
        key: elasticsearch-endpoint
    - secretKey: api-key
      remoteRef:
        key: elasticsearch-api-key
