apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

images:
- name: umbraco
  newName: altinncr.azurecr.io/ghcr.io/altinn/umbraco
  newTag: will-be-replaced

patches:
  - target:
      kind: HTTPRoute
      name: umbraco
    patch: |-
      - op: add
        path: /spec/hostnames
        value:
          - infoportal.prod.dis-core.altinn.cloud
