apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: elasticsearch-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://infoportal-es-at22-g5j8.vault.azure.net"
      serviceAccountRef:
        name: umbraco
