apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

images:
- name: umbraco
  newName: ghcr.io/altinn/umbraco
  newTag: sha256-59e6938a4b198c720c2f1517c4517eef6c4b7e7a29720a2a1603d3e9294c1e44

patches:
  - target:
      kind: HTTPRoute
      name: umbraco
    patch: |-
      - op: add
        path: /spec/hostnames
        value:
          - infoportal.at22.dis-core.altinn.cloud
