apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-infoportal
resources:
  - ../base
  - elasticsearch-secretstore.yaml
  - elasticsearch-secrets.yaml

images:
  - name: umbraco
    newName: altinncr.azurecr.io/ghcr.io/altinn/umbraco
    newTag: will-be-replaced

patches:
  - target:
      kind: Vault
      name: umbraco
    patch: |-
      - op: add
        path: /spec/tags/env
        value: at22
  - target:
      kind: Deployment
      name: umbraco
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Umbraco__Storage__AzureBlob__Media__ConnectionString
          value: https://infoportalmediaat224w17.blob.core.windows.net
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Elasticsearch__Endpoint
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: endpoint
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Elasticsearch__ApiKey
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: api-key
  - target:
      kind: HTTPRoute
      name: umbraco
    patch: |-
      - op: add
        path: /spec/hostnames
        value:
          - infoportal.at22.dis-core.altinn.cloud
