apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

images:
- name: umbraco
  newName: my-registry/umbraco
  newTag: v0.0.1

patches:
  - target:
      kind: HTTPRoute
      name: umbraco
    patch: |-
      - op: add
        path: /spec/hostnames
        value:
          - infoportal.at22.dis-core.altinn.cloud
