name: Publish Syncroot artifacts
run-name: Deploy ${{ inputs.image-tag }}

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Umbraco image tag to deploy'
        required: true
      database:
        type: choice
        description: Which database to use?
        options:
          - Sqlite
          - AzureSQL
        required: true

name: Deploy

        
  # push:
  #   branches:
  #     - main

env:
  SYNCROOT_ARTIFACT_NAME: infoportal/syncroot

permissions:
  contents: read
  id-token: write

concurrency:
  group: publish-flux-artifacts-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  publish-syncroot:
    name: Publish syncroot artifact
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Update image tag
        run: yq -i '(.images[] | select(.name == "umbraco")).newTag = "${{ inputs.image-tag }}"' ./syncroot/at22/kustomization.yaml

      - name: Update db connection string
        if: ${{ inputs.database == "AzureSQL" }}
        run: yq -i '.spec.template.spec.containers[0].env.ConnectionStrings__umbracoDbDSN = "Server=tcp:${UMBRACO_SQL_CONN_FQDN},1433;Initial Catalog=umbraco;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication=\"Active Directory Default\""' ./syncroot/base/deployment.yaml

      - name: Update db provider
        if: ${{ inputs.database == "AzureSQL" }}
        run: yq -i '.spec.template.spec.containers[0].env.ConnectionStrings__umbracoDbDSN_ProviderName = "Microsoft.Data.SqlClient"' ./syncroot/base/deployment.yaml

      - name: Build and push syncroot artifact
        uses: Altinn/altinn-platform/actions/flux/build-push-image@8d4e42eae11efbc3a159aa62fe15ed49954d9df9 # main
        with:
          image_name: ${{ env.SYNCROOT_ARTIFACT_NAME }}
          tag: at22
          workdir: ./syncroot
          azure_subscription_id: ${{ secrets.DIS_SYNCROOT_AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.DIS_SYNCROOT_AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.DIS_SYNCROOT_AZURE_TENANT_ID }}
